name: test-coindcx-websocket-and-audit

on:
  workflow_dispatch:
  push:
    branches: [ main ]  # Future madhe konta hi code push kelyavar auto-run hoil
  schedule:
    - cron: '30 18 * * *'  # IST pramaneloch ratrichya 12:30 AM sathi UTC 18:30 la run hoil

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install "python-socketio==4.6.1" "python-engineio==3.14.2" websocket-client pandas numpy

      - name: Run test (auto-stop after 90s)
        run: timeout 90 python3 -u test_ws.py || true

      - name: Run Data Collection & Audit update
        run: python3 collect.py || true
